### ISSUE TITLE
I needed to add to include <string.h> in include/siMath.h

### ISSUE THREAD

**Issue by UnixJunkie** [baoilleach/pharao#2]
so that it compiles on an Ubuntu 16.04 Linux.

By the way, are you the new maintainer of Pharao?

**Comment by baoilleach** [comment]
To be honest, there's no point filing issues here as I'm not maintaining this. I just checked in the code a few years ago and applied some patches for problems I identified. At that time, Silicos IT was already gone or not responsive or something (I don't remember the details at this point). Since then, I believe that Pharao has been renamed to Align-IT. I don't know if the problems identified in these patches was addressed.
